### PR TITLE
Fixed IndexErrors on missing metadata and TypeErrors on missing tags

### PR DESCRIPTION
**Pull request by D4KU**
I regularly get errors when metadata or tags are missing. I added some error handling, so the download doesn't completely break off. Sorry for only making screenshots and not copying the text. I was lazy at the time...

Screenshot 2021-11-30 004136
Screenshot 2021-12-01 204315
DailyBlinkError

### CODE REVIEW

**Comment by ptrstn** [comment]
Judging on the Screenshot it looks like you're using an old version of dailyblink.

I think this problem already is fixed.

**Comment by D4KU** [comment]
Yes I made the screenshots in an older version, but I updated before fixing the relevant code, and the problems still persisted in the current version. The relevant code also hasn't changed between the two versions.

**Comment by ptrstn** [comment]
This particular blink successfully got downloaded in the [GitHub actions job](https://github.com/ptrstn/dailyblink/runs/4375913362?check_suite_focus=true):

```bash
Run dailyblink
Downloading the free daily Blinks...


english (en):
Bliss More - Light Watkins

Saving book text...
Saving book cover...
Saving audio track #1 - What’s in it for me? Learn how to medita...
Saving audio track #2 - Meditation should be easy....
Saving audio track #3 - To quiet the mind, stop trying to quiet ...
Saving audio track #4 - To help quiet your mind, use a Settling ...
Saving audio track #5 - To make meditation work for you, make a ...
Saving audio track #6 - Meditation leads to relaxation....
Saving audio track #7 - Don’t worry, you’re just de-stressing....
Saving audio track #8 - True mindfulness is a product of meditat...
Saving audio track #9 - Final summary...
Creating playlist file...


german (de):
Geflochtenes Süßgras - Robin Wall Kimmerer

Saving book text...
Saving book cover...
Saving audio track #1 - Was drin ist für dich: Indigene Weisheit...
Saving audio track #2 - Unterschiedliche Welten...
Saving audio track #3 - Die Geschichte des Süßgrases...
Saving audio track #4 - Das Prinzip der Reziprozität...
Saving audio track #5 - Ehrenhafte Ernte...
Saving audio track #6 - Die drei Schwestern...
Saving audio track #7 - Treue der Natur, statt der Nation...
Saving audio track #8 - Fazit...
Creating playlist file...

All blinks were saved under /home/runner/Musik/blinks
```

But todays blink failed somehow.

I will check

**Comment by ptrstn** [comment]
I fixed todays problem in https://github.com/ptrstn/dailyblink/pull/17

I still think your PR was already fixed earlier. 
See: https://github.com/ptrstn/dailyblink/pull/12

**Comment by D4KU** [comment]
Alright, both fixes combined should fix my problems, then. Thank you! :)

**Pull request closed without merging**
